name: "On commit"

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Get dependencies
      run: npm install --no-optional

    - name: Build
      run: npm run build

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Get dependencies
      run: npm install --no-optional

    - name: Check formatting
      run: npm run test:lint

    - name: Check types
      run: npm run test:type

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Get dependencies
      run: npm install --no-optional

    - name: Increase watchers
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Test
      run: npm run test:coverage

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage
